[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/dashboard/mitglieder/*"
  to = "/dashboard/mitglieder/placeholder/index.html"
  status = 200
